apiVersion: apps/v1
kind: Deployment
metadata:
  name: near-dns-prod
  labels:
    app: near-dns-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: near-dns-prod
  template:
    metadata:
      labels:
        app: near-dns-prod
    spec:
      containers:
        - name: near-dns
          image: ghcr.io/kmjayadeep/near-dns/near-dns-backend:1739755642
          imagePullPolicy: Always
          env:
            - name: ENV_TYPE
              value: "production"
            - name: RECONCILE_INTERVAL
              value: "600"
            - name: CLOUDFLARE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: near-dns-secret
                  key: cloudflare_api_key
            - name: CLOUDFLARE_ZONE_ID
              valueFrom:
                secretKeyRef:
                  name: near-dns-secret
                  key: cloudflare_zone_id
