[package]
name = "near-dns-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
near-api = "0.4.0"
reqwest = "0.12.12"
serde = "1.0.217"
serde_json = "1.0.138"
tokio = { version = "1.43.0", features = ["full"] }
