[package]
name = "near-dns-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.29"
near-api = "0.5.0"
reqwest = "0.12.15"
serde = "1.0.217"
serde_json = "1.0.138"
tokio = { version = "1.43.0", features = ["full"] }
