name: Build and Push Backend container

on:
  push:
    branches:
      - main 
    paths:
      - 'near-dns-backend/**'
      - '.github/workflows/build-backend.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/near-dns-backend
          docker build -t $IMAGE_NAME:latest near-dns-backend/

      # Push the Docker image with multiple tags
      - name: Push Docker image with multiple tags
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/near-dns-backend
          TIMESTAMP=$(date +%s)

          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TIMESTAMP
          
          # Push both tags
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$TIMESTAMP
