name: Build and Push Docker Image with Timestamp Tag

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image with multiple tags
      - name: Build Docker image with latest and timestamp tags
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/near-dns-backend
          TIMESTAMP=$(date +%s)
          
          # Build with both tags
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$TIMESTAMP near-dns-backend/

      # Push the Docker image with multiple tags
      - name: Push Docker image with multiple tags
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/near-dns-backend
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          
          # Push both tags
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$TIMESTAMP
