name: Deploy to staging and Prod
on:
  push:
    branches: [main]
    paths:
      - 'near-dns-contract/**'
      - '.github/workflows/deploy-staging-prod.yml'

jobs:
  test:
    uses: ./.github/workflows/test.yml

  deploy-staging:
    environment: staging
    name: Deploy to staging
    needs: [test]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./near-dns-contract
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install cargo-near CLI
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/near/cargo-near/releases/download/cargo-near-v0.13.2/cargo-near-installer.sh | sh
      - name: Deploy to staging
        run: |
          cargo near deploy build-reproducible-wasm "${{ vars.NEAR_CONTRACT_STAGING_ACCOUNT_ID }}" \
            without-init-call \
            network-config "${{ vars.NEAR_CONTRACT_STAGING_NETWORK }}" \
            sign-with-plaintext-private-key \
              --signer-public-key "${{ vars.NEAR_CONTRACT_STAGING_ACCOUNT_PUBLIC_KEY }}" \
              --signer-private-key "${{ secrets.NEAR_CONTRACT_STAGING_ACCOUNT_PRIVATE_KEY }}" \
            send

  deploy-prod:
    environment: prod
    name: Deploy to production
    needs:
    - test
    - deploy-staging
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./near-dns-contract
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install cargo-near CLI
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/near/cargo-near/releases/download/cargo-near-v0.13.2/cargo-near-installer.sh | sh
      - name: Deploy to production
        run: |
          cargo near deploy build-reproducible-wasm "${{ vars.NEAR_CONTRACT_PRODUCTION_ACCOUNT_ID }}" \
            without-init-call \
            network-config "${{ vars.NEAR_CONTRACT_PRODUCTION_NETWORK }}" \
            sign-with-plaintext-private-key \
              --signer-public-key "${{ vars.NEAR_CONTRACT_PRODUCTION_ACCOUNT_PUBLIC_KEY }}" \
              --signer-private-key "${{ secrets.NEAR_CONTRACT_PRODUCTION_ACCOUNT_PRIVATE_KEY }}" \
            send
