name: Undeploy PR from Staging
on:
  pull_request:
    types: [closed]
    paths:
      - 'near-dns-contract/**'
      - '.github/workflows/deploy-pr.yml'
      - '.github/workflows/test.yml'

jobs:
  cleanup-staging:
    name: Cleanup staging PR subaccount
    environment: staging
    runs-on: self-hosted
    permissions:
      contents: read
      id-token: write
    env:
      NEAR_CONTRACT_PR_STAGING_ACCOUNT_ID: gh-${{ github.event.number }}.${{ vars.NEAR_CONTRACT_STAGING_ACCOUNT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Vault Secrets
        id: vault-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: "https://vault.cosmos.cboxlab.com"
          role: auth.jwt.near-dns
          method: jwt
          secrets: |
              homelab/kv/data/near-dns/staging account-privatekey | ACCOUNT_PRIVATE_KEY ;
              homelab/kv/data/near-dns/staging account-publickey | ACCOUNT_PUBLIC_KEY ;

      - name: Install near CLI
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/near/near-cli-rs/releases/download/v0.11.1/near-cli-rs-installer.sh | sh

      - name: Add $HOME/.cargo/bin to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Remove staging account
        run: |
          near account delete-account "${{ env.NEAR_CONTRACT_PR_STAGING_ACCOUNT_ID }}" \
            beneficiary "${{ vars.NEAR_CONTRACT_STAGING_ACCOUNT_ID }}" \
            network-config "${{ vars.NEAR_CONTRACT_STAGING_NETWORK }}" \
            sign-with-plaintext-private-key \
              --signer-public-key "${{ steps.vault-secrets.outputs.ACCOUNT_PUBLIC_KEY }}" \
              --signer-private-key "${{ steps.vault-secrets.outputs.ACCOUNT_PRIVATE_KEY }}" \
            send
